import type { NextPage } from 'next'
import Head from 'next/head'
import Footer from '../src/components/common/Footer'
import { add } from '../src/utils/utils'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <h1 className={styles.title}>
          The Result of 1+2 is <span>{add(1, 2)}</span>
        </h1>
      </main>

      <Footer />
    </div>
  )
}

export default Home
